# Generated by Django 3.0.2 on 2020-01-13 07:06

import dashboard.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=30)),
                ('alternative_phone_number1', models.CharField(blank=True, max_length=30, null=True)),
                ('alternative_phone_number2', models.CharField(blank=True, max_length=30, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET(dashboard.models.get_sentinel_user), related_name='referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
